language: go
go:
  - tip
script:
  - go build ./...
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: wvBbljUQipIFCPAo3LaRNGvoUtc3WbKdSkoKWakDj8xmTKjH/NlWhwaRqZ5G0BK+bCITvNZhvo1jeBHw0T6vmEWoKRdxBXc9qDMSu6wCy/yYuPeSKKcYEpn9KwQfGMklXo8VijDouZzOUittepXw3h0q+kbZzzRw9+dJ7Veed9jWLqGwcDVTcuEqpmGTCG4ub600a4FL+0A6M/gVMgUEnQaGeTDdV4DhbsBLETETDnoo1xvZErcFVP8QZLEBFuAshUOTGlM6cgBrhyI2tkF6SQMZQN+DvmTUZd92POWe64k/YsCR2euk62WkAMwc+ZfYBo5MjAkNWmtMHJ4ckwTu2s6fnfqfKUqoHFrSmD7xsl2ry7K/OrKUGSO6SEFTEDHVodL188MNDNaBrbV8o8IR683z7oKJxfUtS1HsBAoDgCDNCP33Wok8a7KlJXWyTbUUs0JUtyLzBTlZRK4Qrdia7NrTgtGykT1fFlkifVq92QmgPxoPQE2UGPbBacHegj8fVNWg/qv5a6K949RqkGM0wqgTUJ5suQVt+HyHqSKKfV8uYg3qYgsMVZBrbZ3nl5+NBdRXW9lywbF5viRHE3hQngkaRbEO4d1zMbtzuneuy4CT992HK+XEvPID9F4Uq30TWBdzQQuECE8rkdaId9XVRZ0QXQAJYuULlN8qs37XjyE=
  file: marathon_task_exporter
  on:
    repo: apognu/marathon_task_exporter
